### ISSUE TITLE
Image deployment in container app

### ISSUE THREAD

**Issue by adeliab** [dotnet-architecture/eShopOnDapr#108]
Is there a sample of the image deployment in a pipeline?
I saw the bicep files of container apps deployment refer to images like 'eshopdapr/catalog.api:latest'
but I don't see a code that publish the project to this image

**Comment by amolenk** [comment]
Hi @adeliab 
We use GitHub Actions to build the images. Files can be found at: https://github.com/dotnet-architecture/eShopOnDapr/tree/main/.github/workflows
