### ISSUE TITLE
ystem.AggregateException: One or more errors occurred

### ISSUE THREAD

**Issue by jjsuo** [dotnet-architecture/eShopOnDapr#117]
I start project on vs2022, open http://localhost:5104/ show error:

![image](https://user-images.githubusercontent.com/6995664/191649384-ddd8c168-405c-4096-b5d9-8612d93d4812.png)

**Comment by erjain** [comment]
Hi @jjsuo, thanks for posting your query here. The issue is resolved now and can be closed.
