### ISSUE TITLE
Blazor dlls blocked by Sophos

### ISSUE THREAD

**Issue by white-label-development** [dotnet-architecture/eShopOnDapr#118]
Hi. New to Dapr, Blazor and Containers so out on a limb here.

When I run eShopOnDapr I can see the blazor dlls being rejected (by Sophos) in the Chrome network tab. I've tried adding the [BlazorWasmAntivirusProtection](https://github.com/stavroskasidis/BlazorWasmAntivirusProtection) but it doesn't seem to work in this scenario as the dlls are not renamed (I've rebuilt and played around with `<RenameDllsTo>blz</RenameDllsTo>`)

Has anyone encountered and solved this problem as I would really appreciate some pointers. 

Loving Dapr BTW :)

**Comment by erjain** [comment]
Hi @white-label-development, thank you for sharing your query here. Are you still facing this issue?

**Comment by erjain** [comment]
Considering the issue is inactive for a long time, it can be closed now.
