### ISSUE TITLE
Reset filter to All raise an error

### ISSUE THREAD

**Issue by karoldeland** [dotnet-architecture/eShopOnDapr#24]
On the SPA app, the product filtering works well until you reset filters to All. 

![image](https://user-images.githubusercontent.com/13969530/107722604-4a805b00-6cad-11eb-834c-39d3edf1f9f8.png)

**Comment by amolenk** [comment]
Thanks for raising this. I believe it's an issue that we inherited from the original eShopOnContainers. I won't fix it for now as I'm already working on a Blazor version of the frontend. That will probably be ready in a couple of weeks to replace the Angular frontend.
