### ISSUE TITLE
Opening SPA page fails

### ISSUE THREAD

**Issue by samcov** [dotnet-architecture/eShopOnDapr#28]
**Navigating to http://localhost:5104/ gives the following error**:  InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

However, http://localhost:5107/hc-ui works just fine(see pic)
![image](https://user-images.githubusercontent.com/1551314/108444768-19a1a800-7210-11eb-9a8e-429c5b795bb2.png)

**Comment by amolenk** [comment]
Have you tried refreshing `http://localhost:5104` or even stopping/starting the solution? I've come across this error in the past, and then it seemed to be transient.

**Comment by samcov** [comment]
I've tried refreshing it, restarting it, with no success.

Is this an angular thing? I know it's somewhat popular, but I really prefer straight html/js/css, not sure what's going on here, this is/should be the simplest part of the solution :)

**Comment by samcov** [comment]
**Note**: I downloaded the latest with changes to WebSpa, but it still didn't work, but also didn't throw an exception.

However, I tried running it using the command line: **"docker-compose up"**

This worked, the main page came up from http://localhost:5104 redirecting to http://localhost:5104/catalog

There were missing images and functionality, which appears to indicate root directory issues possibly.
![image](https://user-images.githubusercontent.com/1551314/108620170-232d3a80-73df-11eb-99cb-caf345801d19.png)

**Comment by amolenk** [comment]
Hmmm, I can't repro your docker-compose problem with some of the images not loading. I've tested running the solution using `docker-compose up` on both macOS and Windows and that worked.
BTW to buy something in the shop, you need to login first (top-right button). Otherwise, you won't be able to add any items to your basket.
My main focus now is getting the Blazor front-end up & running which will definitely take care of any Angular-related problems ;-)

**Comment by timfun** [comment]
I have been there,   have the same issue when run by visual studio , i will try to run by powershell

**Comment by amolenk** [comment]
Just pushed some fixes that should make the SPA work properly both when running from Visual Studio and Docker Compose directly.

@samcov @timfun Can you check if the latest update works for you?

**Comment by samcov** [comment]
The catalog does come up(with all pictures), but I don't see a login button anywhere.

**Comment by amolenk** [comment]
It's in the top-right, but the visibility is not great with the current background image.

![image](https://user-images.githubusercontent.com/3013979/108761129-c3ee3800-754e-11eb-93e8-4b6abe9c488d.png)

**Comment by samcov** [comment]
Found it!!!

I logged in and was able to add items to the cart, and then check out.

**GREAT Job, Thanks!**

**Comment by timfun** [comment]
@amolenk

> Just pushed some fixes that should make the SPA work properly both when running from Visual Studio and Docker Compose directly.
> 
> @samcov @timfun Can you check if the latest update works for you?

I find a way to make it work when running from Visual Studio. 
           add  the code below to WebSpa.csproj  at the end of  <Target> node.
           <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build:prod" />

I will try your fix  thks
