### ISSUE TITLE
Remove dynamic from DaprEventBus PublishAsync

### ISSUE THREAD

**Issue by tonysneed** [dotnet-architecture/eShopOnDapr#40]
Remove cast to `dynamic` from [DaprEventBus PublishAsync](https://github.com/dotnet-architecture/eShopOnDapr/blob/master/src/BuildingBlocks/EventBus/EventBus/DaprEventBus.cs#L32).

According to @rynowak [here](https://github.com/dapr-dotnet-extensions/dapr-event-bus/issues/1), you don't need to use `dynamic` for polymorphic serialization.

**Comment by amolenk** [comment]
Thanks for raising this! Agree that this should be ‘object’ instead of ‘dynamic’. Will change this.

**Comment by amolenk** [comment]
We'll fix this with the 1.0 release of the Dapr for .NET Developers ebook, as eShopOnDapr serves as the companion sample to the book.

**Comment by amolenk** [comment]
Done
