### ISSUE TITLE
zipkin no records

### ISSUE THREAD

**Issue by HarveyJiang** [dotnet-architecture/eShopOnDapr#41]
hi, use win10 docker desktop run master branche. 
i update this cmmand, add -log-as-json ,but http://localhost:5411/zipkin no records, Everything else is fine. What else needs to be configured , thx.
command: ["./daprd",
      "-app-id", "payment-api",
      "-app-port", "80",
      "-log-level", "debug",
      **"-log-as-json",**
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]

**Comment by fbridger** [comment]
I am experiencing the same issue when running the application through Visual Studio.

Any ideas why no tracing information is not displayed in Zipkin?

**Comment by amolenk** [comment]
This is fixed by #52
There were some invalid '+' characters in the Dapr config file.
