### ISSUE TITLE
Error on deploy to k8s

### ISSUE THREAD

**Issue by vuminhquang** [dotnet-architecture/eShopOnDapr#46]
Hello,
When I use .\start-all.ps1 in "deploy\k8s", I got this error:
![image](https://user-images.githubusercontent.com/20512463/119484556-57b6e680-bd80-11eb-81c5-c4db8719b460.png)
Seems that the error was in
dapr-config.yaml

Thanks

**Comment by vuminhquang** [comment]
Install dapr resolve the error
dapr init -k

**Comment by wjkhappy14** [comment]
dapr init -k
