### ISSUE TITLE
Login report a 404

### ISSUE THREAD

**Issue by ChristPetitjean** [dotnet-architecture/eShopOnDapr#47]
Hello there,

I'm using vscode here.
When I first run `docker-compose up` there was an issue with the build which seems to disapeared somehow at the second composition....

Ok so my catalog is showing:
![image](https://user-images.githubusercontent.com/13761085/119728235-83ff5f80-be73-11eb-9c1e-cb8d24922a7e.png)

But when I click login i came into this:
![image](https://user-images.githubusercontent.com/13761085/119728301-96799900-be73-11eb-8897-8964eea6d66d.png)

FYI: all service are running good:
![image](https://user-images.githubusercontent.com/13761085/119728364-ae511d00-be73-11eb-9f56-8544ab5ff090.png)

and dockers is still happy:
![image](https://user-images.githubusercontent.com/13761085/119728453-caed5500-be73-11eb-974f-f8d59b451659.png)

I'm at a loss here...

ps: I obviously didn't edit anything, and I am just running it.

**Comment by CJ99** [comment]
First of all, you need to upgrade the `Dapr` version to the latest probably. Then, you can probably try the `identity server URL http://localhost:5105/ and http://localhost:5105/.well-known/openid-configuration to see if you can discover the auth endpoints.

**Comment by vishnupn** [comment]
Updated all Dapr packages to latest version but still same issue ..
When i open localhost:5105, i can see ordering api
![Erro](https://user-images.githubusercontent.com/11084786/120278846-67c84c00-c2d3-11eb-845d-e209fc4694a5.jpg)

**Comment by vishnupn** [comment]
This error can occur if the packages in the identity or web status services are failed to restore during docker compose --build.
