### ISSUE TITLE
Roadmap & progress update

### ISSUE THREAD

**Issue by MedAnd** [dotnet-architecture/eShopOnDapr#49]
With continued investment & DAPR project progress, wondering if the eShopOnDapr  team could publish a roadmap? For example is this project still active etc. Thx.

**Comment by amolenk** [comment]
Hi @MedAnd. Yes, the project is active. We're currently working on the last bits of the 1.0 version of the Dapr for .NET Developers ebook (which uses eShopOnDapr as a reference application). When that's out the door, we want to focus on eShopOnDapr updates including a Blazor client UI. Public roadmap is a good idea, we'll look into adding that to the readme.

**Comment by CharlieDigital** [comment]
@amolenk Where will the ebook be published and what is the best channel to follow for notifications? (twitter?)

**Comment by amolenk** [comment]
@CharlieDigital You can find the online version of the book here: https://docs.microsoft.com/dotnet/architecture/dapr-for-net-developers/
This is currently the preview edition. It will be updated to v1 in the coming weeks. That'll be promoted through the @daprdev twitter account

**Comment by amolenk** [comment]
Closing this now. Progress on .NET 6 can be monitored via #62
