### ISSUE TITLE
Run eShopOnDapr from Visual Studio

### ISSUE THREAD

**Issue by JCEdward** [dotnet-architecture/eShopOnDapr#53]
**when i run docker-compose or f5 in visual studio**

> 1>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
1>docker-compose  -f "H:\study\eShopOnDapr\docker-compose.yml" -f "H:\study\eShopOnDapr\docker-compose.override.yml" -p dockercompose16962333610270357271 --no-ansi config
1>[31moption '--no-ansi' is DEPRECATED ! Please use '--ansi' instead.
1>[0mCan't separate key from value
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(209,5): error DT1001: [0mCan't separate key from value
1>Done building project "docker-compose.dcproj" -- FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

**Comment by amolenk** [comment]
Hi @JCEdward. Can you retry with the latest eShopOnDapr version?

**Comment by JCEdward** [comment]
> Hi @JCEdward. Can you retry with the latest eShopOnDapr version?

Currently, this issue does not happen.
