### ISSUE TITLE
invalid variable name "\ufeff"

### ISSUE THREAD

**Issue by lsqtzj** [dotnet-architecture/eShopOnDapr#56]
docker-compose  -f "D:\CSharp\eShopOnDapr\docker-compose.yml" -f "D:\CSharp\eShopOnDapr\docker-compose.override.yml" -p dockercompose1387013637272126799 --ansi never config
invalid variable name "\ufeff"
![image](https://user-images.githubusercontent.com/4635861/133598860-36b9af7b-2b5e-47d2-a6cc-d1236b1da634.png)

**Comment by AntoCanza** [comment]
Are you using docker desktop under windows? if yes i had the same problem. i have fixed it:
Settings -> Experimental Features -> make sure the "Use  Docker compose v2" is not checked

**Comment by Gsonovb** [comment]
HI,

I have the same problem
I modified the ". Env" file encoding format to utf8, not utf8 with BOM

**Comment by amolenk** [comment]
BOM is removed from .env file
