### ISSUE TITLE
Run on Azure Container Apps

### ISSUE THREAD

**Issue by amolenk** [dotnet-architecture/eShopOnDapr#63]
Add deployments files to run eShop on the new Azure Container Apps service.

**Comment by jedjohan** [comment]
any progress on this ? need help ?

**Comment by amolenk** [comment]
Hi, see #81. You should be able to run on ACA by deploying main.bicep. Will add docs and merge when I get back from my skiing trip 😊

**Comment by jedjohan** [comment]
Will try next innovation days, good job and thanks

**Comment by amolenk** [comment]
Support for ACA has been pushed. See https://github.com/dotnet-architecture/eShopOnDapr/blob/main/docs/run-eshop.md#run-eshopondapr-on-azure-container-apps
