### ISSUE TITLE
run minikube

### ISSUE THREAD

**Issue by wjkhappy14** [dotnet-architecture/eShopOnDapr#66]
run the [helm install myeshop .]     and all microservices are healthy, but i can't  navigate to http://localhost:30000 to view the eShopOnDapr UI.
why ?

**Comment by amolenk** [comment]
Haven't tried Minikube yet myself. Can you access the healthcheck UI at http://localhost:30007/healthchecks-ui?

**Comment by amolenk** [comment]
Hi @wjkhappy14 

I've pushed some K8s fixes (see #76). If you're still running into issues, can you check with the latest version?

**Comment by expbk** [comment]
@amolenk were you able to run it on minikube ? If yes, can you please share how you accessed the eShopOnDapr UI ?

**Comment by amolenk** [comment]
Hi @expbk,
I'm not using minikube myself and haven't had time yet to test it.
