### ISSUE TITLE
docker-compose is not working when run via visual studio

### ISSUE THREAD

**Issue by expbk** [dotnet-architecture/eShopOnDapr#73]
Unable to run the project in visual studio when docker-compose is set as startup project.
Getting the error shown in the image below
![image](https://user-images.githubusercontent.com/87414495/145778173-a6a6d97c-ffa7-49b7-8834-632817e5e294.png)

**Comment by Sen-Gupta** [comment]
We also faced this problem. VS2022 latest version,  Docker Desktop Latest.
Here is a little more information.

![image](https://user-images.githubusercontent.com/8068582/145972943-ebd0e4c0-2a56-4385-888c-45b51e5f0052.png)

**Comment by ajaysingh77** [comment]
When I tried Visual Studio, fortunately, I haven't seen this issue. I will try to see if I can replicate this.

**Comment by Sen-Gupta** [comment]
If it helps any one, this is a known issue here: https://github.com/microsoft/DockerTools/issues/320.

@ajaysingh77 what is your configuration?  VS, Net Core and Docker Desktop?

**Comment by RobHLowry** [comment]
I did a clean install yesterday and I got the same exception.  VS 2022 Community, Docker Desktop, Dapr 1.5.1.

**Comment by ajaysingh77** [comment]
@Sen-Gupta I am currently using Visual Studio 2022(17.0.2), Net Core and Docker Desktop (4.3.1) on Windows 11.

**Comment by Sen-Gupta** [comment]
@ajaysingh77 I see, your VS stands a couple of build behind from latest which is
![image](https://user-images.githubusercontent.com/8068582/146570025-d22cd6bb-d4c7-454f-bef6-56734ab330e9.png)

**Comment by ajaysingh77** [comment]
@Sen-Gupta  finally I am able to replicate the issue by cloning the repo in a different location and running it from visual studio.
but the solution (workaround1) mentioned in [https://github.com/microsoft/DockerTools/issues/320](url) also pointed by you works for me.

**Comment by amolenk** [comment]
Fix has shipped in VS 17.1
