### ISSUE TITLE
Unauthorized 401 error when adding to Basket

### ISSUE THREAD

**Issue by kevingbb** [dotnet-architecture/eShopOnDapr#74]
I get a 401 Unauthorized error message when trying to add any item to the shopping cart after successfully logging in when running in a remote Kubernetes environment.

I can successfully run eShopOnDapr on my local machine through the use of docker-compose up. I am also able to successfully deploy the solution to a remote AKS cluster through the use of the Helm chart. All of the pods start up and I am able to successfully login using Bob or Alice. I can see the catalog items and filter on them. However, once I log in and try to add an item to the shopping cart I get a 401 Unauthorized error back from the API Gateway. Based on my understanding it goes to the API Gateway pod, which then redirects to Web Shopping Aggregator Pod and that is where it hits the 401 Unauthorized error message.

I checked the API Gateway and Shopping Aggregator logs, but nothing stands out. From what I can tell logging in works, Authorization to Basket API works as it successfully retrieves the shopping cart, it only seems to be the Web Shopping Aggregator. 
I checked if I can save and retrieve state from the DAPR statestore and that works as expected.

I have attached a screenshot showing the successful catalog and basket GETs, and the 401 Unauthorized messages in the browser.
<img width="908" alt="Screenshot 2022-01-11 at 17 42 15" src="https://user-images.githubusercontent.com/19918338/148984734-0e33b1cf-1896-447d-b69b-3b0d9ae82525.png">

**Comment by amolenk** [comment]
Thanks for reporting this @kevingbb, I'll look into it.

**Comment by amolenk** [comment]
Turns out the manifest for the web shopping aggregator service didn't contain the correct setting for the location of the Identity service. Therefor, the aggregator couldn't validate the incoming auth token and raised the 401.

I've fixed it now along with some other K8s issues (see #76). Could you try again with the latest version?

**Comment by kevingbb** [comment]
I grabbed the latest changes and it is now working as expected.

**Comment by dereklew** [comment]
Hi 

Seems like if we run from VS, this issue will occurs.
