### ISSUE TITLE
Setting eshop on AKS with Internet access?

### ISSUE THREAD

**Issue by ManojG1978** [dotnet-architecture/eShopOnDapr#86]
Other than creating an Ingress resource (which is not part of the repo), are there simple steps to expose the blazorclient to the internet (just like in eshopOnContainers)? I see that all services are nodeports and need some plumbing to expose to the internet. Same goes to web status and auth.

**Comment by amolenk** [comment]
The Kubernetes instructions (https://github.com/dotnet-architecture/eShopOnDapr/blob/main/docs/run-eshop.md) now include an NGINX ingress controller. Instructions do not include setting up DNS though, that's still something you'd have to do yourself and dependent on type of K8s cluster.
