### ISSUE TITLE
Using Visual Studio to launch the project, getting the Unauthenticated error despite already login.

### ISSUE THREAD

**Issue by dereklew** [dotnet-architecture/eShopOnDapr#89]
Using Visual Studio to launch the project, getting the Unauthenticated error despite already login.

[{"traceId":"9c302b6e711d097a994a6a3580004115","id":"707e5f2a1782df16","kind":"CLIENT","name":"calllocal/basket-api/api/v1/basket/","timestamp":1647694630584448,"duration":667744,"localEndpoint":{"serviceName":"webshoppingapigw","ipv4":"172.18.0.10"},"tags":{"dapr.api":"GET /v1.0/invoke/basket-api/method/api/v1/basket/","dapr.protocol":"http","dapr.status_code":"401","error":"UNAUTHENTICATED","net.peer.name":"basket-api","opencensus.status_description":"Unauthenticated","rpc.service":"ServiceInvocation"}},{"traceId":"9c302b6e711d097a994a6a3580004115","parentId":"707e5f2a1782df16","id":"56903cd7fc4313ff","kind":"SERVER","name":"calllocal/basket-api/api/v1/basket/","timestamp":1647694630585212,"duration":666297,"localEndpoint":{"serviceName":"basket-api","ipv4":"172.18.0.16"},"tags":{"dapr.api":"/dapr.proto.internals.v1.ServiceInvocation/CallLocal","dapr.invoke_method":"api/v1/basket/","dapr.protocol":"grpc","rpc.service":"ServiceInvocation"}}]

**Comment by dereklew** [comment]
Getting this

www-authenticate: Bearer error="invalid_token", error_description="The issuer 'http://localhost:5105' is invalid"

**Comment by dereklew** [comment]
Resolved myself.

In Identity.api/appsettings.json, change the parameter to  "IssuerUrl": "http://localhost:5105"

**Comment by wjkhappy14** [comment]
POST http://loocalhost:5202/hub/notificationhub/negotiate?negotiateVersion=1 401 (Unauthorized)

**Comment by wjkhappy14** [comment]
docker-compose.override
identity-api
- IssuerUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105

**Comment by amolenk** [comment]
Fixed by #91
