### ISSUE TITLE
Blazor Client app not daprized

### ISSUE THREAD

**Issue by ffrankozz** [dotnet-architecture/eShopOnDapr#96]
Just a simple  question: Is there any particular reason that the Blazor Client app is not daprized?

**Comment by Xilosof** [comment]
I will try to answer your question, even though I am not the developer of this repository. If I'm wrong, I hope the owners will help. 

I think this demonstrates the flexibility of the architecture and the possibility of partial implementation of dapr. That is, dapr is implemented in the entire part behind the "public api", which allows independent developers to use standard ways of communicating with the api of our application. 

You decide whether to use dapr for your frontend application or any other part of the application

**Comment by ffrankozz** [comment]
@amolenk  Oh yes, Blazor runs in the browser. I forgot that.  Thank you for the reply. However, if we had used an aspnetcore mvc frontend, instead of Blazor Client, we might be daprizing it, I suppose.

**Comment by amolenk** [comment]
@ffrankozz Yes, I agree. If the frontend would run server-side, we wouldn't need the API gateway and it would make sense to just use a Dapr sidecar to reach the back-end services.
